export const products = [
  {
    id: 1,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 6,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 7,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 8,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 9,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 10,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 11,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 12,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 13,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 14,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 15,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 16,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 17,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 18,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 19,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 20,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 21,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 22,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 23,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 24,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 25,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 26,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },

  {
    id: 27,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 28,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 29,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 30,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 31,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 32,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 33,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 34,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 35,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 36,
    title: 'Product Title',
    price: 123,
    description: 'lorem ipsum',
    category: ['Category'],
    image: 'https://via.placeholder.com/150',
  },
];
